version: '3.1'
services:
  ghost:
    image: ghost
    ports:
      - 2368:2368
    environment:
      NODE_ENV: development
    
  email:
    image: mailhog/mailhog
    container_name: mailhog_container
    ports:
      - "8025:8025"

  hello:
    image: hashicorp/http-echo
    command: ["-text", "Hello!"]
    ports:
      - "5678:5678"
