version: '3.1'
services:

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80

  ghost: # Listens on port 2368 internally
    image: ghost
    environment:
      NODE_ENV: development
    
  email: # Listens on port 8025 internally
    image: mailhog/mailhog
    container_name: mailhog_container

  hello: # Listens on port 5678 internally
    image: hashicorp/http-echo
    command: ["-text", "Hello!"]
