version: '3.1'
services:

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx_image
    container_name: nginx_container
    ports:
      - 8080:80
      - 8081:81
      - 8082:82
      - 8083:83 # Do this for the email server sending email

  ghost: # Listens on port 2368 internally
    image: ghost
    container_name: ghost_container
    environment:
      NODE_ENV: development
      url: http://localhost:8081
    
  hello: # Listens on port 5678 internally
    image: hashicorp/http-echo
    container_name: hello_container
    command: ["-text", "Hello!"]

  email: # Listens on port 8025 internally and 1025 intenally for the email server
    image: mailhog/mailhog
    container_name: mailhog_container
